  <?php

  use Illuminate\Database\Seeder;

  class IconsTableSeeder extends Seeder
  {
      /**
       * Run the database seeds.
       *
       * @return void
       */
      public function run()
      {
        DB::table('icons')->insert([
           ["ref"=>"fa-500px","name"=>"500px","id"=>2],
           ["ref"=>"fa-address-book","name"=>"address book","id"=>3],
           ["ref"=>"fa-address-book-o","name"=>"address book-o","id"=>4],
           ["ref"=>"fa-address-card","name"=>"address card","id"=>5],
           ["ref"=>"fa-address-card-o","name"=>"address card-o","id"=>6],
           ["ref"=>"fa-adjust","name"=>"adjust","id"=>7],
           ["ref"=>"fa-adn","name"=>"adn","id"=>8],
           ["ref"=>"fa-align-center","name"=>"align center","id"=>9],
           ["ref"=>"fa-align-justify","name"=>"align justify","id"=>10],
           ["ref"=>"fa-align-left","name"=>"align left","id"=>11],
           ["ref"=>"fa-align-right","name"=>"align right","id"=>12],
           ["ref"=>"fa-amazon","name"=>"amazon","id"=>13],
           ["ref"=>"fa-ambulance","name"=>"ambulance","id"=>14],
           ["ref"=>"fa-american-sign-language-interpreting","name"=>"american sign-language-interpreting","id"=>15],
           ["ref"=>"fa-anchor","name"=>"anchor","id"=>16],
           ["ref"=>"fa-android","name"=>"android","id"=>17],
           ["ref"=>"fa-angellist","name"=>"angellist","id"=>18],
           ["ref"=>"fa-angle-double-down","name"=>"angle double-down","id"=>19],
           ["ref"=>"fa-angle-double-left","name"=>"angle double-left","id"=>20],
           ["ref"=>"fa-angle-double-right","name"=>"angle double-right","id"=>21],
           ["ref"=>"fa-angle-double-up","name"=>"angle double-up","id"=>22],
           ["ref"=>"fa-angle-down","name"=>"angle down","id"=>23],
           ["ref"=>"fa-angle-left","name"=>"angle left","id"=>24],
           ["ref"=>"fa-angle-right","name"=>"angle right","id"=>25],
           ["ref"=>"fa-angle-up","name"=>"angle up","id"=>26],
           ["ref"=>"fa-apple","name"=>"apple","id"=>27],
           ["ref"=>"fa-archive","name"=>"archive","id"=>28],
           ["ref"=>"fa-area-chart","name"=>"area chart","id"=>29],
           ["ref"=>"fa-arrow-circle-down","name"=>"arrow circle-down","id"=>30],
           ["ref"=>"fa-arrow-circle-left","name"=>"arrow circle-left","id"=>31],
           ["ref"=>"fa-arrow-circle-o-down","name"=>"arrow circle-o-down","id"=>32],
           ["ref"=>"fa-arrow-circle-o-left","name"=>"arrow circle-o-left","id"=>33],
           ["ref"=>"fa-arrow-circle-o-right","name"=>"arrow circle-o-right","id"=>34],
           ["ref"=>"fa-arrow-circle-o-up","name"=>"arrow circle-o-up","id"=>35],
           ["ref"=>"fa-arrow-circle-right","name"=>"arrow circle-right","id"=>36],
           ["ref"=>"fa-arrow-circle-up","name"=>"arrow circle-up","id"=>37],
           ["ref"=>"fa-arrow-down","name"=>"arrow down","id"=>38],
           ["ref"=>"fa-arrow-left","name"=>"arrow left","id"=>39],
           ["ref"=>"fa-arrow-right","name"=>"arrow right","id"=>40],
           ["ref"=>"fa-arrow-up","name"=>"arrow up","id"=>41],
           ["ref"=>"fa-arrows","name"=>"arrows","id"=>42],
           ["ref"=>"fa-arrows-alt","name"=>"arrows alt","id"=>43],
           ["ref"=>"fa-arrows-h","name"=>"arrows h","id"=>44],
           ["ref"=>"fa-arrows-v","name"=>"arrows v","id"=>45],
           ["ref"=>"fa-assistive-listening-systems","name"=>"assistive listening-systems","id"=>47],
           ["ref"=>"fa-asterisk","name"=>"asterisk","id"=>48],
           ["ref"=>"fa-at","name"=>"at","id"=>49],
           ["ref"=>"fa-audio-description","name"=>"audio description","id"=>50],
           ["ref"=>"fa-backward","name"=>"backward","id"=>52],
           ["ref"=>"fa-balance-scale","name"=>"balance scale","id"=>53],
           ["ref"=>"fa-ban","name"=>"ban","id"=>54],
           ["ref"=>"fa-bandcamp","name"=>"bandcamp","id"=>55],
           ["ref"=>"fa-bar-chart","name"=>"bar chart","id"=>57],
           ["ref"=>"fa-barcode","name"=>"barcode","id"=>59],
           ["ref"=>"fa-bars","name"=>"bars","id"=>60],
           ["ref"=>"fa-bath","name"=>"bath","id"=>61],
           ["ref"=>"fa-battery-empty","name"=>"battery empty","id"=>69],
           ["ref"=>"fa-battery-full","name"=>"battery full","id"=>70],
           ["ref"=>"fa-battery-half","name"=>"battery half","id"=>71],
           ["ref"=>"fa-battery-quarter","name"=>"battery quarter","id"=>72],
           ["ref"=>"fa-battery-three-quarters","name"=>"battery three-quarters","id"=>73],
           ["ref"=>"fa-bed","name"=>"bed","id"=>74],
           ["ref"=>"fa-beer","name"=>"beer","id"=>75],
           ["ref"=>"fa-behance","name"=>"behance","id"=>76],
           ["ref"=>"fa-behance-square","name"=>"behance square","id"=>77],
           ["ref"=>"fa-bell","name"=>"bell","id"=>78],
           ["ref"=>"fa-bell-o","name"=>"bell o","id"=>79],
           ["ref"=>"fa-bell-slash","name"=>"bell slash","id"=>80],
           ["ref"=>"fa-bell-slash-o","name"=>"bell slash-o","id"=>81],
           ["ref"=>"fa-bicycle","name"=>"bicycle","id"=>82],
           ["ref"=>"fa-binoculars","name"=>"binoculars","id"=>83],
           ["ref"=>"fa-birthday-cake","name"=>"birthday cake","id"=>84],
           ["ref"=>"fa-bitbucket","name"=>"bitbucket","id"=>85],
           ["ref"=>"fa-bitbucket-square","name"=>"bitbucket square","id"=>86],
           ["ref"=>"fa-black-tie","name"=>"black tie","id"=>88],
           ["ref"=>"fa-blind","name"=>"blind","id"=>89],
           ["ref"=>"fa-bluetooth","name"=>"bluetooth","id"=>90],
           ["ref"=>"fa-bluetooth-b","name"=>"bluetooth b","id"=>91],
           ["ref"=>"fa-bold","name"=>"bold","id"=>92],
           ["ref"=>"fa-bolt","name"=>"bolt","id"=>93],
           ["ref"=>"fa-bomb","name"=>"bomb","id"=>94],
           ["ref"=>"fa-book","name"=>"book","id"=>95],
           ["ref"=>"fa-bookmark","name"=>"bookmark","id"=>96],
           ["ref"=>"fa-bookmark-o","name"=>"bookmark o","id"=>97],
           ["ref"=>"fa-braille","name"=>"braille","id"=>98],
           ["ref"=>"fa-briefcase","name"=>"briefcase","id"=>99],
           ["ref"=>"fa-btc","name"=>"btc","id"=>100],
           ["ref"=>"fa-bug","name"=>"bug","id"=>101],
           ["ref"=>"fa-building","name"=>"building","id"=>102],
           ["ref"=>"fa-building-o","name"=>"building o","id"=>103],
           ["ref"=>"fa-bullhorn","name"=>"bullhorn","id"=>104],
           ["ref"=>"fa-bullseye","name"=>"bullseye","id"=>105],
           ["ref"=>"fa-bus","name"=>"bus","id"=>106],
           ["ref"=>"fa-buysellads","name"=>"buysellads","id"=>107],
           ["ref"=>"fa-calculator","name"=>"calculator","id"=>109],
           ["ref"=>"fa-calendar","name"=>"calendar","id"=>110],
           ["ref"=>"fa-calendar-check-o","name"=>"calendar check-o","id"=>111],
           ["ref"=>"fa-calendar-minus-o","name"=>"calendar minus-o","id"=>112],
           ["ref"=>"fa-calendar-o","name"=>"calendar o","id"=>113],
           ["ref"=>"fa-calendar-plus-o","name"=>"calendar plus-o","id"=>114],
           ["ref"=>"fa-calendar-times-o","name"=>"calendar times-o","id"=>115],
           ["ref"=>"fa-camera","name"=>"camera","id"=>116],
           ["ref"=>"fa-camera-retro","name"=>"camera retro","id"=>117],
           ["ref"=>"fa-car","name"=>"car","id"=>118],
           ["ref"=>"fa-caret-down","name"=>"caret down","id"=>119],
           ["ref"=>"fa-caret-left","name"=>"caret left","id"=>120],
           ["ref"=>"fa-caret-right","name"=>"caret right","id"=>121],
           ["ref"=>"fa-caret-square-o-down","name"=>"caret square-o-down","id"=>122],
           ["ref"=>"fa-caret-square-o-left","name"=>"caret square-o-left","id"=>123],
           ["ref"=>"fa-caret-square-o-right","name"=>"caret square-o-right","id"=>124],
           ["ref"=>"fa-caret-square-o-up","name"=>"caret square-o-up","id"=>125],
           ["ref"=>"fa-caret-up","name"=>"caret up","id"=>126],
           ["ref"=>"fa-cart-arrow-down","name"=>"cart arrow-down","id"=>127],
           ["ref"=>"fa-cart-plus","name"=>"cart plus","id"=>128],
           ["ref"=>"fa-cc","name"=>"cc","id"=>129],
           ["ref"=>"fa-cc-amex","name"=>"cc amex","id"=>130],
           ["ref"=>"fa-cc-diners-club","name"=>"cc diners-club","id"=>131],
           ["ref"=>"fa-cc-discover","name"=>"cc discover","id"=>132],
           ["ref"=>"fa-cc-jcb","name"=>"cc jcb","id"=>133],
           ["ref"=>"fa-cc-mastercard","name"=>"cc mastercard","id"=>134],
           ["ref"=>"fa-cc-paypal","name"=>"cc paypal","id"=>135],
           ["ref"=>"fa-cc-stripe","name"=>"cc stripe","id"=>136],
           ["ref"=>"fa-cc-visa","name"=>"cc visa","id"=>137],
           ["ref"=>"fa-certificate","name"=>"certificate","id"=>138],
           ["ref"=>"fa-chain-broken","name"=>"chain broken","id"=>140],
           ["ref"=>"fa-check","name"=>"check","id"=>141],
           ["ref"=>"fa-check-circle","name"=>"check circle","id"=>142],
           ["ref"=>"fa-check-circle-o","name"=>"check circle-o","id"=>143],
           ["ref"=>"fa-check-square","name"=>"check square","id"=>144],
           ["ref"=>"fa-check-square-o","name"=>"check square-o","id"=>145],
           ["ref"=>"fa-chevron-circle-down","name"=>"chevron circle-down","id"=>146],
           ["ref"=>"fa-chevron-circle-left","name"=>"chevron circle-left","id"=>147],
           ["ref"=>"fa-chevron-circle-right","name"=>"chevron circle-right","id"=>148],
           ["ref"=>"fa-chevron-circle-up","name"=>"chevron circle-up","id"=>149],
           ["ref"=>"fa-chevron-down","name"=>"chevron down","id"=>150],
           ["ref"=>"fa-chevron-left","name"=>"chevron left","id"=>151],
           ["ref"=>"fa-chevron-right","name"=>"chevron right","id"=>152],
           ["ref"=>"fa-chevron-up","name"=>"chevron up","id"=>153],
           ["ref"=>"fa-child","name"=>"child","id"=>154],
           ["ref"=>"fa-chrome","name"=>"chrome","id"=>155],
           ["ref"=>"fa-circle","name"=>"circle","id"=>156],
           ["ref"=>"fa-circle-o","name"=>"circle o","id"=>157],
           ["ref"=>"fa-circle-o-notch","name"=>"circle o-notch","id"=>158],
           ["ref"=>"fa-circle-thin","name"=>"circle thin","id"=>159],
           ["ref"=>"fa-clipboard","name"=>"clipboard","id"=>160],
           ["ref"=>"fa-clock-o","name"=>"clock o","id"=>161],
           ["ref"=>"fa-clone","name"=>"clone","id"=>162],
           ["ref"=>"fa-cloud","name"=>"cloud","id"=>164],
           ["ref"=>"fa-cloud-download","name"=>"cloud download","id"=>165],
           ["ref"=>"fa-cloud-upload","name"=>"cloud upload","id"=>166],
           ["ref"=>"fa-code","name"=>"code","id"=>168],
           ["ref"=>"fa-code-fork","name"=>"code fork","id"=>169],
           ["ref"=>"fa-codepen","name"=>"codepen","id"=>170],
           ["ref"=>"fa-codiepie","name"=>"codiepie","id"=>171],
           ["ref"=>"fa-coffee","name"=>"coffee","id"=>172],
           ["ref"=>"fa-cog","name"=>"cog","id"=>173],
           ["ref"=>"fa-cogs","name"=>"cogs","id"=>174],
           ["ref"=>"fa-columns","name"=>"columns","id"=>175],
           ["ref"=>"fa-comment","name"=>"comment","id"=>176],
           ["ref"=>"fa-comment-o","name"=>"comment o","id"=>177],
           ["ref"=>"fa-commenting","name"=>"commenting","id"=>178],
           ["ref"=>"fa-commenting-o","name"=>"commenting o","id"=>179],
           ["ref"=>"fa-comments","name"=>"comments","id"=>180],
           ["ref"=>"fa-comments-o","name"=>"comments o","id"=>181],
           ["ref"=>"fa-compass","name"=>"compass","id"=>182],
           ["ref"=>"fa-compress","name"=>"compress","id"=>183],
           ["ref"=>"fa-connectdevelop","name"=>"connectdevelop","id"=>184],
           ["ref"=>"fa-contao","name"=>"contao","id"=>185],
           ["ref"=>"fa-copyright","name"=>"copyright","id"=>187],
           ["ref"=>"fa-creative-commons","name"=>"creative commons","id"=>188],
           ["ref"=>"fa-credit-card","name"=>"credit card","id"=>189],
           ["ref"=>"fa-credit-card-alt","name"=>"credit card-alt","id"=>190],
           ["ref"=>"fa-crop","name"=>"crop","id"=>191],
           ["ref"=>"fa-crosshairs","name"=>"crosshairs","id"=>192],
           ["ref"=>"fa-css3","name"=>"css3","id"=>193],
           ["ref"=>"fa-cube","name"=>"cube","id"=>194],
           ["ref"=>"fa-cubes","name"=>"cubes","id"=>195],
           ["ref"=>"fa-cutlery","name"=>"cutlery","id"=>197],
           ["ref"=>"fa-dashcube","name"=>"dashcube","id"=>199],
           ["ref"=>"fa-database","name"=>"database","id"=>200],
           ["ref"=>"fa-deaf","name"=>"deaf","id"=>201],
           ["ref"=>"fa-delicious","name"=>"delicious","id"=>204],
           ["ref"=>"fa-desktop","name"=>"desktop","id"=>205],
           ["ref"=>"fa-deviantart","name"=>"deviantart","id"=>206],
           ["ref"=>"fa-diamond","name"=>"diamond","id"=>207],
           ["ref"=>"fa-digg","name"=>"digg","id"=>208],
           ["ref"=>"fa-dot-circle-o","name"=>"dot circle-o","id"=>210],
           ["ref"=>"fa-download","name"=>"download","id"=>211],
           ["ref"=>"fa-dribbble","name"=>"dribbble","id"=>212],
           ["ref"=>"fa-dropbox","name"=>"dropbox","id"=>215],
           ["ref"=>"fa-drupal","name"=>"drupal","id"=>216],
           ["ref"=>"fa-edge","name"=>"edge","id"=>217],
           ["ref"=>"fa-eercast","name"=>"eercast","id"=>219],
           ["ref"=>"fa-eject","name"=>"eject","id"=>220],
           ["ref"=>"fa-ellipsis-h","name"=>"ellipsis h","id"=>221],
           ["ref"=>"fa-ellipsis-v","name"=>"ellipsis v","id"=>222],
           ["ref"=>"fa-empire","name"=>"empire","id"=>223],
           ["ref"=>"fa-envelope","name"=>"envelope","id"=>224],
           ["ref"=>"fa-envelope-o","name"=>"envelope o","id"=>225],
           ["ref"=>"fa-envelope-open","name"=>"envelope open","id"=>226],
           ["ref"=>"fa-envelope-open-o","name"=>"envelope open-o","id"=>227],
           ["ref"=>"fa-envelope-square","name"=>"envelope square","id"=>228],
           ["ref"=>"fa-envira","name"=>"envira","id"=>229],
           ["ref"=>"fa-eraser","name"=>"eraser","id"=>230],
           ["ref"=>"fa-etsy","name"=>"etsy","id"=>231],
           ["ref"=>"fa-eur","name"=>"eur","id"=>232],
           ["ref"=>"fa-exchange","name"=>"exchange","id"=>234],
           ["ref"=>"fa-exclamation","name"=>"exclamation","id"=>235],
           ["ref"=>"fa-exclamation-circle","name"=>"exclamation circle","id"=>236],
           ["ref"=>"fa-exclamation-triangle","name"=>"exclamation triangle","id"=>237],
           ["ref"=>"fa-expand","name"=>"expand","id"=>238],
           ["ref"=>"fa-expeditedssl","name"=>"expeditedssl","id"=>239],
           ["ref"=>"fa-external-link","name"=>"external link","id"=>240],
           ["ref"=>"fa-external-link-square","name"=>"external link-square","id"=>241],
           ["ref"=>"fa-eye","name"=>"eye","id"=>242],
           ["ref"=>"fa-eye-slash","name"=>"eye slash","id"=>243],
           ["ref"=>"fa-eyedropper","name"=>"eyedropper","id"=>244],
           ["ref"=>"fa-facebook","name"=>"facebook","id"=>246],
           ["ref"=>"fa-facebook-official","name"=>"facebook official","id"=>248],
           ["ref"=>"fa-facebook-square","name"=>"facebook square","id"=>249],
           ["ref"=>"fa-fast-backward","name"=>"fast backward","id"=>250],
           ["ref"=>"fa-fast-forward","name"=>"fast forward","id"=>251],
           ["ref"=>"fa-fax","name"=>"fax","id"=>252],
           ["ref"=>"fa-female","name"=>"female","id"=>254],
           ["ref"=>"fa-fighter-jet","name"=>"fighter jet","id"=>255],
           ["ref"=>"fa-file","name"=>"file","id"=>256],
           ["ref"=>"fa-file-archive-o","name"=>"file archive-o","id"=>257],
           ["ref"=>"fa-file-audio-o","name"=>"file audio-o","id"=>258],
           ["ref"=>"fa-file-code-o","name"=>"file code-o","id"=>259],
           ["ref"=>"fa-file-excel-o","name"=>"file excel-o","id"=>260],
           ["ref"=>"fa-file-image-o","name"=>"file image-o","id"=>261],
           ["ref"=>"fa-file-o","name"=>"file o","id"=>263],
           ["ref"=>"fa-file-pdf-o","name"=>"file pdf-o","id"=>264],
           ["ref"=>"fa-file-powerpoint-o","name"=>"file powerpoint-o","id"=>267],
           ["ref"=>"fa-file-text","name"=>"file text","id"=>269],
           ["ref"=>"fa-file-text-o","name"=>"file text-o","id"=>270],
           ["ref"=>"fa-file-video-o","name"=>"file video-o","id"=>271],
           ["ref"=>"fa-file-word-o","name"=>"file word-o","id"=>272],
           ["ref"=>"fa-files-o","name"=>"files o","id"=>274],
           ["ref"=>"fa-film","name"=>"film","id"=>275],
           ["ref"=>"fa-filter","name"=>"filter","id"=>276],
           ["ref"=>"fa-fire","name"=>"fire","id"=>277],
           ["ref"=>"fa-fire-extinguisher","name"=>"fire extinguisher","id"=>278],
           ["ref"=>"fa-firefox","name"=>"firefox","id"=>279],
           ["ref"=>"fa-first-order","name"=>"first order","id"=>280],
           ["ref"=>"fa-flag","name"=>"flag","id"=>281],
           ["ref"=>"fa-flag-checkered","name"=>"flag checkered","id"=>282],
           ["ref"=>"fa-flag-o","name"=>"flag o","id"=>283],
           ["ref"=>"fa-flask","name"=>"flask","id"=>285],
           ["ref"=>"fa-flickr","name"=>"flickr","id"=>286],
           ["ref"=>"fa-floppy-o","name"=>"floppy o","id"=>287],
           ["ref"=>"fa-folder","name"=>"folder","id"=>288],
           ["ref"=>"fa-folder-o","name"=>"folder o","id"=>289],
           ["ref"=>"fa-folder-open","name"=>"folder open","id"=>290],
           ["ref"=>"fa-folder-open-o","name"=>"folder open-o","id"=>291],
           ["ref"=>"fa-font","name"=>"font","id"=>292],
           ["ref"=>"fa-font-awesome","name"=>"font awesome","id"=>293],
           ["ref"=>"fa-fonticons","name"=>"fonticons","id"=>294],
           ["ref"=>"fa-fort-awesome","name"=>"fort awesome","id"=>295],
           ["ref"=>"fa-forumbee","name"=>"forumbee","id"=>296],
           ["ref"=>"fa-forward","name"=>"forward","id"=>297],
           ["ref"=>"fa-foursquare","name"=>"foursquare","id"=>298],
           ["ref"=>"fa-free-code-camp","name"=>"free code-camp","id"=>299],
           ["ref"=>"fa-frown-o","name"=>"frown o","id"=>300],
           ["ref"=>"fa-futbol-o","name"=>"futbol o","id"=>301],
           ["ref"=>"fa-gamepad","name"=>"gamepad","id"=>302],
           ["ref"=>"fa-gavel","name"=>"gavel","id"=>303],
           ["ref"=>"fa-gbp","name"=>"gbp","id"=>304],
           ["ref"=>"fa-genderless","name"=>"genderless","id"=>308],
           ["ref"=>"fa-get-pocket","name"=>"get pocket","id"=>309],
           ["ref"=>"fa-gg","name"=>"gg","id"=>310],
           ["ref"=>"fa-gg-circle","name"=>"gg circle","id"=>311],
           ["ref"=>"fa-gift","name"=>"gift","id"=>312],
           ["ref"=>"fa-git","name"=>"git","id"=>313],
           ["ref"=>"fa-git-square","name"=>"git square","id"=>314],
           ["ref"=>"fa-github","name"=>"github","id"=>315],
           ["ref"=>"fa-github-alt","name"=>"github alt","id"=>316],
           ["ref"=>"fa-github-square","name"=>"github square","id"=>317],
           ["ref"=>"fa-gitlab","name"=>"gitlab","id"=>318],
           ["ref"=>"fa-glass","name"=>"glass","id"=>320],
           ["ref"=>"fa-glide","name"=>"glide","id"=>321],
           ["ref"=>"fa-glide-g","name"=>"glide g","id"=>322],
           ["ref"=>"fa-globe","name"=>"globe","id"=>323],
           ["ref"=>"fa-google","name"=>"google","id"=>324],
           ["ref"=>"fa-google-plus","name"=>"google plus","id"=>325],
           ["ref"=>"fa-google-plus-official","name"=>"google plus-official","id"=>327],
           ["ref"=>"fa-google-plus-square","name"=>"google plus-square","id"=>328],
           ["ref"=>"fa-google-wallet","name"=>"google wallet","id"=>329],
           ["ref"=>"fa-graduation-cap","name"=>"graduation cap","id"=>330],
           ["ref"=>"fa-gratipay","name"=>"gratipay","id"=>331],
           ["ref"=>"fa-grav","name"=>"grav","id"=>332],
           ["ref"=>"fa-h-square","name"=>"h square","id"=>334],
           ["ref"=>"fa-hacker-news","name"=>"hacker news","id"=>335],
           ["ref"=>"fa-hand-lizard-o","name"=>"hand lizard-o","id"=>337],
           ["ref"=>"fa-hand-o-down","name"=>"hand o-down","id"=>338],
           ["ref"=>"fa-hand-o-left","name"=>"hand o-left","id"=>339],
           ["ref"=>"fa-hand-o-right","name"=>"hand o-right","id"=>340],
           ["ref"=>"fa-hand-o-up","name"=>"hand o-up","id"=>341],
           ["ref"=>"fa-hand-paper-o","name"=>"hand paper-o","id"=>342],
           ["ref"=>"fa-hand-peace-o","name"=>"hand peace-o","id"=>343],
           ["ref"=>"fa-hand-pointer-o","name"=>"hand pointer-o","id"=>344],
           ["ref"=>"fa-hand-rock-o","name"=>"hand rock-o","id"=>345],
           ["ref"=>"fa-hand-scissors-o","name"=>"hand scissors-o","id"=>346],
           ["ref"=>"fa-hand-spock-o","name"=>"hand spock-o","id"=>347],
           ["ref"=>"fa-handshake-o","name"=>"handshake o","id"=>349],
           ["ref"=>"fa-hashtag","name"=>"hashtag","id"=>351],
           ["ref"=>"fa-hdd-o","name"=>"hdd o","id"=>352],
           ["ref"=>"fa-header","name"=>"header","id"=>353],
           ["ref"=>"fa-headphones","name"=>"headphones","id"=>354],
           ["ref"=>"fa-heart","name"=>"heart","id"=>355],
           ["ref"=>"fa-heart-o","name"=>"heart o","id"=>356],
           ["ref"=>"fa-heartbeat","name"=>"heartbeat","id"=>357],
           ["ref"=>"fa-history","name"=>"history","id"=>358],
           ["ref"=>"fa-home","name"=>"home","id"=>359],
           ["ref"=>"fa-hospital-o","name"=>"hospital o","id"=>360],
           ["ref"=>"fa-hourglass","name"=>"hourglass","id"=>362],
           ["ref"=>"fa-hourglass-end","name"=>"hourglass end","id"=>366],
           ["ref"=>"fa-hourglass-half","name"=>"hourglass half","id"=>367],
           ["ref"=>"fa-hourglass-o","name"=>"hourglass o","id"=>368],
           ["ref"=>"fa-hourglass-start","name"=>"hourglass start","id"=>369],
           ["ref"=>"fa-houzz","name"=>"houzz","id"=>370],
           ["ref"=>"fa-html5","name"=>"html5","id"=>371],
           ["ref"=>"fa-i-cursor","name"=>"i cursor","id"=>372],
           ["ref"=>"fa-id-badge","name"=>"id badge","id"=>373],
           ["ref"=>"fa-id-card","name"=>"id card","id"=>374],
           ["ref"=>"fa-id-card-o","name"=>"id card-o","id"=>375],
           ["ref"=>"fa-ils","name"=>"ils","id"=>376],
           ["ref"=>"fa-imdb","name"=>"imdb","id"=>378],
           ["ref"=>"fa-inbox","name"=>"inbox","id"=>379],
           ["ref"=>"fa-indent","name"=>"indent","id"=>380],
           ["ref"=>"fa-industry","name"=>"industry","id"=>381],
           ["ref"=>"fa-info","name"=>"info","id"=>382],
           ["ref"=>"fa-info-circle","name"=>"info circle","id"=>383],
           ["ref"=>"fa-inr","name"=>"inr","id"=>384],
           ["ref"=>"fa-instagram","name"=>"instagram","id"=>385],
           ["ref"=>"fa-internet-explorer","name"=>"internet explorer","id"=>387],
           ["ref"=>"fa-ioxhost","name"=>"ioxhost","id"=>389],
           ["ref"=>"fa-italic","name"=>"italic","id"=>390],
           ["ref"=>"fa-joomla","name"=>"joomla","id"=>391],
           ["ref"=>"fa-jpy","name"=>"jpy","id"=>392],
           ["ref"=>"fa-jsfiddle","name"=>"jsfiddle","id"=>393],
           ["ref"=>"fa-key","name"=>"key","id"=>394],
           ["ref"=>"fa-keyboard-o","name"=>"keyboard o","id"=>395],
           ["ref"=>"fa-krw","name"=>"krw","id"=>396],
           ["ref"=>"fa-language","name"=>"language","id"=>397],
           ["ref"=>"fa-laptop","name"=>"laptop","id"=>398],
           ["ref"=>"fa-lastfm","name"=>"lastfm","id"=>399],
           ["ref"=>"fa-lastfm-square","name"=>"lastfm square","id"=>400],
           ["ref"=>"fa-leaf","name"=>"leaf","id"=>401],
           ["ref"=>"fa-leanpub","name"=>"leanpub","id"=>402],
           ["ref"=>"fa-lemon-o","name"=>"lemon o","id"=>404],
           ["ref"=>"fa-level-down","name"=>"level down","id"=>405],
           ["ref"=>"fa-level-up","name"=>"level up","id"=>406],
           ["ref"=>"fa-life-ring","name"=>"life ring","id"=>409],
           ["ref"=>"fa-lightbulb-o","name"=>"lightbulb o","id"=>411],
           ["ref"=>"fa-line-chart","name"=>"line chart","id"=>412],
           ["ref"=>"fa-link","name"=>"link","id"=>413],
           ["ref"=>"fa-linkedin","name"=>"linkedin","id"=>414],
           ["ref"=>"fa-linkedin-square","name"=>"linkedin square","id"=>415],
           ["ref"=>"fa-linode","name"=>"linode","id"=>416],
           ["ref"=>"fa-linux","name"=>"linux","id"=>417],
           ["ref"=>"fa-list","name"=>"list","id"=>418],
           ["ref"=>"fa-list-alt","name"=>"list alt","id"=>419],
           ["ref"=>"fa-list-ol","name"=>"list ol","id"=>420],
           ["ref"=>"fa-list-ul","name"=>"list ul","id"=>421],
           ["ref"=>"fa-location-arrow","name"=>"location arrow","id"=>422],
           ["ref"=>"fa-lock","name"=>"lock","id"=>423],
           ["ref"=>"fa-long-arrow-down","name"=>"long arrow-down","id"=>424],
           ["ref"=>"fa-long-arrow-left","name"=>"long arrow-left","id"=>425],
           ["ref"=>"fa-long-arrow-right","name"=>"long arrow-right","id"=>426],
           ["ref"=>"fa-long-arrow-up","name"=>"long arrow-up","id"=>427],
           ["ref"=>"fa-low-vision","name"=>"low vision","id"=>428],
           ["ref"=>"fa-magic","name"=>"magic","id"=>429],
           ["ref"=>"fa-magnet","name"=>"magnet","id"=>430],
           ["ref"=>"fa-male","name"=>"male","id"=>434],
           ["ref"=>"fa-map","name"=>"map","id"=>435],
           ["ref"=>"fa-map-marker","name"=>"map marker","id"=>436],
           ["ref"=>"fa-map-o","name"=>"map o","id"=>437],
           ["ref"=>"fa-map-pin","name"=>"map pin","id"=>438],
           ["ref"=>"fa-map-signs","name"=>"map signs","id"=>439],
           ["ref"=>"fa-mars","name"=>"mars","id"=>440],
           ["ref"=>"fa-mars-double","name"=>"mars double","id"=>441],
           ["ref"=>"fa-mars-stroke","name"=>"mars stroke","id"=>442],
           ["ref"=>"fa-mars-stroke-h","name"=>"mars stroke-h","id"=>443],
           ["ref"=>"fa-mars-stroke-v","name"=>"mars stroke-v","id"=>444],
           ["ref"=>"fa-maxcdn","name"=>"maxcdn","id"=>445],
           ["ref"=>"fa-meanpath","name"=>"meanpath","id"=>446],
           ["ref"=>"fa-medium","name"=>"medium","id"=>447],
           ["ref"=>"fa-medkit","name"=>"medkit","id"=>448],
           ["ref"=>"fa-meetup","name"=>"meetup","id"=>449],
           ["ref"=>"fa-meh-o","name"=>"meh o","id"=>450],
           ["ref"=>"fa-mercury","name"=>"mercury","id"=>451],
           ["ref"=>"fa-microchip","name"=>"microchip","id"=>452],
           ["ref"=>"fa-microphone","name"=>"microphone","id"=>453],
           ["ref"=>"fa-microphone-slash","name"=>"microphone slash","id"=>454],
           ["ref"=>"fa-minus","name"=>"minus","id"=>455],
           ["ref"=>"fa-minus-circle","name"=>"minus circle","id"=>456],
           ["ref"=>"fa-minus-square","name"=>"minus square","id"=>457],
           ["ref"=>"fa-minus-square-o","name"=>"minus square-o","id"=>458],
           ["ref"=>"fa-mixcloud","name"=>"mixcloud","id"=>459],
           ["ref"=>"fa-mobile","name"=>"mobile","id"=>460],
           ["ref"=>"fa-modx","name"=>"modx","id"=>462],
           ["ref"=>"fa-money","name"=>"money","id"=>463],
           ["ref"=>"fa-moon-o","name"=>"moon o","id"=>464],
           ["ref"=>"fa-motorcycle","name"=>"motorcycle","id"=>466],
           ["ref"=>"fa-mouse-pointer","name"=>"mouse pointer","id"=>467],
           ["ref"=>"fa-music","name"=>"music","id"=>468],
           ["ref"=>"fa-neuter","name"=>"neuter","id"=>470],
           ["ref"=>"fa-newspaper-o","name"=>"newspaper o","id"=>471],
           ["ref"=>"fa-object-group","name"=>"object group","id"=>472],
           ["ref"=>"fa-object-ungroup","name"=>"object ungroup","id"=>473],
           ["ref"=>"fa-odnoklassniki","name"=>"odnoklassniki","id"=>474],
           ["ref"=>"fa-odnoklassniki-square","name"=>"odnoklassniki square","id"=>475],
           ["ref"=>"fa-opencart","name"=>"opencart","id"=>476],
           ["ref"=>"fa-openid","name"=>"openid","id"=>477],
           ["ref"=>"fa-opera","name"=>"opera","id"=>478],
           ["ref"=>"fa-optin-monster","name"=>"optin monster","id"=>479],
           ["ref"=>"fa-outdent","name"=>"outdent","id"=>480],
           ["ref"=>"fa-pagelines","name"=>"pagelines","id"=>481],
           ["ref"=>"fa-paint-brush","name"=>"paint brush","id"=>482],
           ["ref"=>"fa-paper-plane","name"=>"paper plane","id"=>483],
           ["ref"=>"fa-paper-plane-o","name"=>"paper plane-o","id"=>484],
           ["ref"=>"fa-paperclip","name"=>"paperclip","id"=>485],
           ["ref"=>"fa-paragraph","name"=>"paragraph","id"=>486],
           ["ref"=>"fa-pause","name"=>"pause","id"=>488],
           ["ref"=>"fa-pause-circle","name"=>"pause circle","id"=>489],
           ["ref"=>"fa-pause-circle-o","name"=>"pause circle-o","id"=>490],
           ["ref"=>"fa-paw","name"=>"paw","id"=>491],
           ["ref"=>"fa-paypal","name"=>"paypal","id"=>492],
           ["ref"=>"fa-pencil","name"=>"pencil","id"=>493],
           ["ref"=>"fa-pencil-square","name"=>"pencil square","id"=>494],
           ["ref"=>"fa-pencil-square-o","name"=>"pencil square-o","id"=>495],
           ["ref"=>"fa-percent","name"=>"percent","id"=>496],
           ["ref"=>"fa-phone","name"=>"phone","id"=>497],
           ["ref"=>"fa-phone-square","name"=>"phone square","id"=>498],
           ["ref"=>"fa-picture-o","name"=>"picture o","id"=>500],
           ["ref"=>"fa-pie-chart","name"=>"pie chart","id"=>501],
           ["ref"=>"fa-pied-piper","name"=>"pied piper","id"=>502],
           ["ref"=>"fa-pied-piper-alt","name"=>"pied piper-alt","id"=>503],
           ["ref"=>"fa-pied-piper-pp","name"=>"pied piper-pp","id"=>504],
           ["ref"=>"fa-pinterest","name"=>"pinterest","id"=>505],
           ["ref"=>"fa-pinterest-p","name"=>"pinterest p","id"=>506],
           ["ref"=>"fa-pinterest-square","name"=>"pinterest square","id"=>507],
           ["ref"=>"fa-plane","name"=>"plane","id"=>508],
           ["ref"=>"fa-play","name"=>"play","id"=>509],
           ["ref"=>"fa-play-circle","name"=>"play circle","id"=>510],
           ["ref"=>"fa-play-circle-o","name"=>"play circle-o","id"=>511],
           ["ref"=>"fa-plug","name"=>"plug","id"=>512],
           ["ref"=>"fa-plus","name"=>"plus","id"=>513],
           ["ref"=>"fa-plus-circle","name"=>"plus circle","id"=>514],
           ["ref"=>"fa-plus-square","name"=>"plus square","id"=>515],
           ["ref"=>"fa-plus-square-o","name"=>"plus square-o","id"=>516],
           ["ref"=>"fa-podcast","name"=>"podcast","id"=>517],
           ["ref"=>"fa-power-off","name"=>"power off","id"=>518],
           ["ref"=>"fa-print","name"=>"print","id"=>519],
           ["ref"=>"fa-product-hunt","name"=>"product hunt","id"=>520],
           ["ref"=>"fa-puzzle-piece","name"=>"puzzle piece","id"=>521],
           ["ref"=>"fa-qq","name"=>"qq","id"=>522],
           ["ref"=>"fa-qrcode","name"=>"qrcode","id"=>523],
           ["ref"=>"fa-question","name"=>"question","id"=>524],
           ["ref"=>"fa-question-circle","name"=>"question circle","id"=>525],
           ["ref"=>"fa-question-circle-o","name"=>"question circle-o","id"=>526],
           ["ref"=>"fa-quora","name"=>"quora","id"=>527],
           ["ref"=>"fa-quote-left","name"=>"quote left","id"=>528],
           ["ref"=>"fa-quote-right","name"=>"quote right","id"=>529],
           ["ref"=>"fa-random","name"=>"random","id"=>531],
           ["ref"=>"fa-ravelry","name"=>"ravelry","id"=>532],
           ["ref"=>"fa-rebel","name"=>"rebel","id"=>533],
           ["ref"=>"fa-recycle","name"=>"recycle","id"=>534],
           ["ref"=>"fa-reddit","name"=>"reddit","id"=>535],
           ["ref"=>"fa-reddit-alien","name"=>"reddit alien","id"=>536],
           ["ref"=>"fa-reddit-square","name"=>"reddit square","id"=>537],
           ["ref"=>"fa-refresh","name"=>"refresh","id"=>538],
           ["ref"=>"fa-registered","name"=>"registered","id"=>539],
           ["ref"=>"fa-renren","name"=>"renren","id"=>541],
           ["ref"=>"fa-repeat","name"=>"repeat","id"=>543],
           ["ref"=>"fa-reply","name"=>"reply","id"=>544],
           ["ref"=>"fa-reply-all","name"=>"reply all","id"=>545],
           ["ref"=>"fa-retweet","name"=>"retweet","id"=>547],
           ["ref"=>"fa-road","name"=>"road","id"=>549],
           ["ref"=>"fa-rocket","name"=>"rocket","id"=>550],
           ["ref"=>"fa-rss","name"=>"rss","id"=>554],
           ["ref"=>"fa-rss-square","name"=>"rss square","id"=>555],
           ["ref"=>"fa-rub","name"=>"rub","id"=>556],
           ["ref"=>"fa-safari","name"=>"safari","id"=>560],
           ["ref"=>"fa-scissors","name"=>"scissors","id"=>562],
           ["ref"=>"fa-scribd","name"=>"scribd","id"=>563],
           ["ref"=>"fa-search","name"=>"search","id"=>564],
           ["ref"=>"fa-search-minus","name"=>"search minus","id"=>565],
           ["ref"=>"fa-search-plus","name"=>"search plus","id"=>566],
           ["ref"=>"fa-sellsy","name"=>"sellsy","id"=>567],
           ["ref"=>"fa-server","name"=>"server","id"=>570],
           ["ref"=>"fa-share","name"=>"share","id"=>571],
           ["ref"=>"fa-share-alt","name"=>"share alt","id"=>572],
           ["ref"=>"fa-share-alt-square","name"=>"share alt-square","id"=>573],
           ["ref"=>"fa-share-square","name"=>"share square","id"=>574],
           ["ref"=>"fa-share-square-o","name"=>"share square-o","id"=>575],
           ["ref"=>"fa-shield","name"=>"shield","id"=>578],
           ["ref"=>"fa-ship","name"=>"ship","id"=>579],
           ["ref"=>"fa-shirtsinbulk","name"=>"shirtsinbulk","id"=>580],
           ["ref"=>"fa-shopping-bag","name"=>"shopping bag","id"=>581],
           ["ref"=>"fa-shopping-basket","name"=>"shopping basket","id"=>582],
           ["ref"=>"fa-shopping-cart","name"=>"shopping cart","id"=>583],
           ["ref"=>"fa-shower","name"=>"shower","id"=>584],
           ["ref"=>"fa-sign-in","name"=>"sign in","id"=>585],
           ["ref"=>"fa-sign-language","name"=>"sign language","id"=>586],
           ["ref"=>"fa-sign-out","name"=>"sign out","id"=>587],
           ["ref"=>"fa-signal","name"=>"signal","id"=>588],
           ["ref"=>"fa-simplybuilt","name"=>"simplybuilt","id"=>590],
           ["ref"=>"fa-sitemap","name"=>"sitemap","id"=>591],
           ["ref"=>"fa-skyatlas","name"=>"skyatlas","id"=>592],
           ["ref"=>"fa-skype","name"=>"skype","id"=>593],
           ["ref"=>"fa-slack","name"=>"slack","id"=>594],
           ["ref"=>"fa-sliders","name"=>"sliders","id"=>595],
           ["ref"=>"fa-slideshare","name"=>"slideshare","id"=>596],
           ["ref"=>"fa-smile-o","name"=>"smile o","id"=>597],
           ["ref"=>"fa-snapchat","name"=>"snapchat","id"=>598],
           ["ref"=>"fa-snapchat-ghost","name"=>"snapchat ghost","id"=>599],
           ["ref"=>"fa-snapchat-square","name"=>"snapchat square","id"=>600],
           ["ref"=>"fa-snowflake-o","name"=>"snowflake o","id"=>601],
           ["ref"=>"fa-sort","name"=>"sort","id"=>603],
           ["ref"=>"fa-sort-alpha-asc","name"=>"sort alpha-asc","id"=>604],
           ["ref"=>"fa-sort-alpha-desc","name"=>"sort alpha-desc","id"=>605],
           ["ref"=>"fa-sort-amount-asc","name"=>"sort amount-asc","id"=>606],
           ["ref"=>"fa-sort-amount-desc","name"=>"sort amount-desc","id"=>607],
           ["ref"=>"fa-sort-asc","name"=>"sort asc","id"=>608],
           ["ref"=>"fa-sort-desc","name"=>"sort desc","id"=>609],
           ["ref"=>"fa-sort-numeric-asc","name"=>"sort numeric-asc","id"=>611],
           ["ref"=>"fa-sort-numeric-desc","name"=>"sort numeric-desc","id"=>612],
           ["ref"=>"fa-soundcloud","name"=>"soundcloud","id"=>614],
           ["ref"=>"fa-space-shuttle","name"=>"space shuttle","id"=>615],
           ["ref"=>"fa-spinner","name"=>"spinner","id"=>616],
           ["ref"=>"fa-spoon","name"=>"spoon","id"=>617],
           ["ref"=>"fa-spotify","name"=>"spotify","id"=>618],
           ["ref"=>"fa-square","name"=>"square","id"=>619],
           ["ref"=>"fa-square-o","name"=>"square o","id"=>620],
           ["ref"=>"fa-stack-exchange","name"=>"stack exchange","id"=>621],
           ["ref"=>"fa-stack-overflow","name"=>"stack overflow","id"=>622],
           ["ref"=>"fa-star","name"=>"star","id"=>623],
           ["ref"=>"fa-star-half","name"=>"star half","id"=>624],
           ["ref"=>"fa-star-half-o","name"=>"star half-o","id"=>627],
           ["ref"=>"fa-star-o","name"=>"star o","id"=>628],
           ["ref"=>"fa-steam","name"=>"steam","id"=>629],
           ["ref"=>"fa-steam-square","name"=>"steam square","id"=>630],
           ["ref"=>"fa-step-backward","name"=>"step backward","id"=>631],
           ["ref"=>"fa-step-forward","name"=>"step forward","id"=>632],
           ["ref"=>"fa-stethoscope","name"=>"stethoscope","id"=>633],
           ["ref"=>"fa-sticky-note","name"=>"sticky note","id"=>634],
           ["ref"=>"fa-sticky-note-o","name"=>"sticky note-o","id"=>635],
           ["ref"=>"fa-stop","name"=>"stop","id"=>636],
           ["ref"=>"fa-stop-circle","name"=>"stop circle","id"=>637],
           ["ref"=>"fa-stop-circle-o","name"=>"stop circle-o","id"=>638],
           ["ref"=>"fa-street-view","name"=>"street view","id"=>639],
           ["ref"=>"fa-strikethrough","name"=>"strikethrough","id"=>640],
           ["ref"=>"fa-stumbleupon","name"=>"stumbleupon","id"=>641],
           ["ref"=>"fa-stumbleupon-circle","name"=>"stumbleupon circle","id"=>642],
           ["ref"=>"fa-subscript","name"=>"subscript","id"=>643],
           ["ref"=>"fa-subway","name"=>"subway","id"=>644],
           ["ref"=>"fa-suitcase","name"=>"suitcase","id"=>645],
           ["ref"=>"fa-sun-o","name"=>"sun o","id"=>646],
           ["ref"=>"fa-superpowers","name"=>"superpowers","id"=>647],
           ["ref"=>"fa-superscript","name"=>"superscript","id"=>648],
           ["ref"=>"fa-table","name"=>"table","id"=>650],
           ["ref"=>"fa-tablet","name"=>"tablet","id"=>651],
           ["ref"=>"fa-tachometer","name"=>"tachometer","id"=>652],
           ["ref"=>"fa-tag","name"=>"tag","id"=>653],
           ["ref"=>"fa-tags","name"=>"tags","id"=>654],
           ["ref"=>"fa-tasks","name"=>"tasks","id"=>655],
           ["ref"=>"fa-taxi","name"=>"taxi","id"=>656],
           ["ref"=>"fa-telegram","name"=>"telegram","id"=>657],
           ["ref"=>"fa-television","name"=>"television","id"=>658],
           ["ref"=>"fa-tencent-weibo","name"=>"tencent weibo","id"=>659],
           ["ref"=>"fa-terminal","name"=>"terminal","id"=>660],
           ["ref"=>"fa-text-height","name"=>"text height","id"=>661],
           ["ref"=>"fa-text-width","name"=>"text width","id"=>662],
           ["ref"=>"fa-th","name"=>"th","id"=>663],
           ["ref"=>"fa-th-large","name"=>"th large","id"=>664],
           ["ref"=>"fa-th-list","name"=>"th list","id"=>665],
           ["ref"=>"fa-themeisle","name"=>"themeisle","id"=>666],
           ["ref"=>"fa-thermometer-empty","name"=>"thermometer empty","id"=>673],
           ["ref"=>"fa-thermometer-full","name"=>"thermometer full","id"=>674],
           ["ref"=>"fa-thermometer-half","name"=>"thermometer half","id"=>675],
           ["ref"=>"fa-thermometer-quarter","name"=>"thermometer quarter","id"=>676],
           ["ref"=>"fa-thermometer-three-quarters","name"=>"thermometer three-quarters","id"=>677],
           ["ref"=>"fa-thumb-tack","name"=>"thumb tack","id"=>678],
           ["ref"=>"fa-thumbs-down","name"=>"thumbs down","id"=>679],
           ["ref"=>"fa-thumbs-o-down","name"=>"thumbs o-down","id"=>680],
           ["ref"=>"fa-thumbs-o-up","name"=>"thumbs o-up","id"=>681],
           ["ref"=>"fa-thumbs-up","name"=>"thumbs up","id"=>682],
           ["ref"=>"fa-ticket","name"=>"ticket","id"=>683],
           ["ref"=>"fa-times","name"=>"times","id"=>684],
           ["ref"=>"fa-times-circle","name"=>"times circle","id"=>685],
           ["ref"=>"fa-times-circle-o","name"=>"times circle-o","id"=>686],
           ["ref"=>"fa-tint","name"=>"tint","id"=>689],
           ["ref"=>"fa-toggle-off","name"=>"toggle off","id"=>692],
           ["ref"=>"fa-toggle-on","name"=>"toggle on","id"=>693],
           ["ref"=>"fa-trademark","name"=>"trademark","id"=>696],
           ["ref"=>"fa-train","name"=>"train","id"=>697],
           ["ref"=>"fa-transgender","name"=>"transgender","id"=>698],
           ["ref"=>"fa-transgender-alt","name"=>"transgender alt","id"=>699],
           ["ref"=>"fa-trash","name"=>"trash","id"=>700],
           ["ref"=>"fa-trash-o","name"=>"trash o","id"=>701],
           ["ref"=>"fa-tree","name"=>"tree","id"=>702],
           ["ref"=>"fa-trello","name"=>"trello","id"=>703],
           ["ref"=>"fa-tripadvisor","name"=>"tripadvisor","id"=>704],
           ["ref"=>"fa-trophy","name"=>"trophy","id"=>705],
           ["ref"=>"fa-truck","name"=>"truck","id"=>706],
           ["ref"=>"fa-try","name"=>"try","id"=>707],
           ["ref"=>"fa-tty","name"=>"tty","id"=>708],
           ["ref"=>"fa-tumblr","name"=>"tumblr","id"=>709],
           ["ref"=>"fa-tumblr-square","name"=>"tumblr square","id"=>710],
           ["ref"=>"fa-twitch","name"=>"twitch","id"=>713],
           ["ref"=>"fa-twitter","name"=>"twitter","id"=>714],
           ["ref"=>"fa-twitter-square","name"=>"twitter square","id"=>715],
           ["ref"=>"fa-umbrella","name"=>"umbrella","id"=>716],
           ["ref"=>"fa-underline","name"=>"underline","id"=>717],
           ["ref"=>"fa-undo","name"=>"undo","id"=>718],
           ["ref"=>"fa-universal-access","name"=>"universal access","id"=>719],
           ["ref"=>"fa-university","name"=>"university","id"=>720],
           ["ref"=>"fa-unlock","name"=>"unlock","id"=>722],
           ["ref"=>"fa-unlock-alt","name"=>"unlock alt","id"=>723],
           ["ref"=>"fa-upload","name"=>"upload","id"=>725],
           ["ref"=>"fa-usb","name"=>"usb","id"=>726],
           ["ref"=>"fa-usd","name"=>"usd","id"=>727],
           ["ref"=>"fa-user","name"=>"user","id"=>728],
           ["ref"=>"fa-user-circle","name"=>"user circle","id"=>729],
           ["ref"=>"fa-user-circle-o","name"=>"user circle-o","id"=>730],
           ["ref"=>"fa-user-md","name"=>"user md","id"=>731],
           ["ref"=>"fa-user-o","name"=>"user o","id"=>732],
           ["ref"=>"fa-user-plus","name"=>"user plus","id"=>733],
           ["ref"=>"fa-user-secret","name"=>"user secret","id"=>734],
           ["ref"=>"fa-user-times","name"=>"user times","id"=>735],
           ["ref"=>"fa-users","name"=>"users","id"=>736],
           ["ref"=>"fa-venus","name"=>"venus","id"=>739],
           ["ref"=>"fa-venus-double","name"=>"venus double","id"=>740],
           ["ref"=>"fa-venus-mars","name"=>"venus mars","id"=>741],
           ["ref"=>"fa-viacoin","name"=>"viacoin","id"=>742],
           ["ref"=>"fa-viadeo","name"=>"viadeo","id"=>743],
           ["ref"=>"fa-viadeo-square","name"=>"viadeo square","id"=>744],
           ["ref"=>"fa-video-camera","name"=>"video camera","id"=>745],
           ["ref"=>"fa-vimeo","name"=>"vimeo","id"=>746],
           ["ref"=>"fa-vimeo-square","name"=>"vimeo square","id"=>747],
           ["ref"=>"fa-vine","name"=>"vine","id"=>748],
           ["ref"=>"fa-vk","name"=>"vk","id"=>749],
           ["ref"=>"fa-volume-control-phone","name"=>"volume control-phone","id"=>750],
           ["ref"=>"fa-volume-down","name"=>"volume down","id"=>751],
           ["ref"=>"fa-volume-off","name"=>"volume off","id"=>752],
           ["ref"=>"fa-volume-up","name"=>"volume up","id"=>753],
           ["ref"=>"fa-weibo","name"=>"weibo","id"=>756],
           ["ref"=>"fa-weixin","name"=>"weixin","id"=>757],
           ["ref"=>"fa-whatsapp","name"=>"whatsapp","id"=>758],
           ["ref"=>"fa-wheelchair","name"=>"wheelchair","id"=>759],
           ["ref"=>"fa-wheelchair-alt","name"=>"wheelchair alt","id"=>760],
           ["ref"=>"fa-wifi","name"=>"wifi","id"=>761],
           ["ref"=>"fa-wikipedia-w","name"=>"wikipedia w","id"=>762],
           ["ref"=>"fa-window-close","name"=>"window close","id"=>763],
           ["ref"=>"fa-window-close-o","name"=>"window close-o","id"=>764],
           ["ref"=>"fa-window-maximize","name"=>"window maximize","id"=>765],
           ["ref"=>"fa-window-minimize","name"=>"window minimize","id"=>766],
           ["ref"=>"fa-window-restore","name"=>"window restore","id"=>767],
           ["ref"=>"fa-windows","name"=>"windows","id"=>768],
           ["ref"=>"fa-wordpress","name"=>"wordpress","id"=>770],
           ["ref"=>"fa-wpbeginner","name"=>"wpbeginner","id"=>771],
           ["ref"=>"fa-wpexplorer","name"=>"wpexplorer","id"=>772],
           ["ref"=>"fa-wpforms","name"=>"wpforms","id"=>773],
           ["ref"=>"fa-wrench","name"=>"wrench","id"=>774],
           ["ref"=>"fa-xing","name"=>"xing","id"=>775],
           ["ref"=>"fa-xing-square","name"=>"xing square","id"=>776],
           ["ref"=>"fa-y-combinator","name"=>"y combinator","id"=>777],
           ["ref"=>"fa-yahoo","name"=>"yahoo","id"=>779],
           ["ref"=>"fa-yelp","name"=>"yelp","id"=>782],
           ["ref"=>"fa-yoast","name"=>"yoast","id"=>784],
           ["ref"=>"fa-youtube","name"=>"youtube","id"=>785],
           ["ref"=>"fa-youtube-play","name"=>"youtube play","id"=>786],
           ["ref"=>"fa-youtube-square","name"=>"youtube square","id"=>1]
         ]);
      }
  }
